"""
nasus_code_engineer.py
Nasus M05 -- Code Engineer
Runtime: analyze_spec, generate, debug, refactor, review, route_envelope + demo
"""
from __future__ import annotations
import json, re
from typing import Union
from nasus_module_registry import ModuleID, NasusEnvelope, NasusStatus  # noqa: F401
from nasus_code_engineer_schema import (
    CodeBlock, CodeError, CodeResult, CodeStatus, CodeStyle,
    CodeTask, Language, Spec, validate_code_output,
)

MODULE_ID   = "M05"
MODULE_NAME = "Code Engineer"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _count_lines(code: str) -> int:
    return sum(1 for line in code.splitlines() if line.strip())

def _make_block(language: Language, code: str, filename: str, description: str) -> CodeBlock:
    return CodeBlock(language=language, code=code, filename=filename,
                     description=description, line_count=_count_lines(code))

def _error(description: str, code: str, message: str) -> CodeError:
    return CodeError(description=description, error_code=code, message=message)

_EXTENSIONS = {
    Language.PYTHON: ".py", Language.JAVASCRIPT: ".js", Language.TYPESCRIPT: ".ts",
    Language.BASH: ".sh", Language.SQL: ".sql", Language.HTML_CSS: ".html",
    Language.RUST: ".rs", Language.GO: ".go",
}
def _ext(lang: Language) -> str:
    return _EXTENSIONS.get(lang, ".txt")

# ---------------------------------------------------------------------------
# 1. analyze_spec
# ---------------------------------------------------------------------------
def analyze_spec(spec: Spec) -> dict:
    """Classify task complexity, detect language patterns and risk flags."""
    dl = spec.description.lower()
    if len(spec.description) < 80 and not spec.context_code:
        complexity = "low"
    elif len(spec.requirements) > 5 or spec.max_lines > 150:
        complexity = "high"
    else:
        complexity = "medium"
    patterns = []
    if any(k in dl for k in ("client","api","http","request","endpoint")): patterns.append("HTTP Client")
    if any(k in dl for k in ("class","object","inherit","base")): patterns.append("OOP")
    if any(k in dl for k in ("async","await","concurrent","parallel")): patterns.append("Async/Await")
    if any(k in dl for k in ("retry","backoff","resilient")): patterns.append("Retry/Backoff")
    if any(k in dl for k in ("test","unit","pytest","jest")): patterns.append("Unit Testing")
    if any(k in dl for k in ("factory","builder","singleton")): patterns.append("Creational Pattern")
    async_needed = any(k in dl for k in ("async","await","httpx"))
    risk_flags = []
    if spec.max_lines < 20 and complexity == "high":
        risk_flags.append("max_lines may be too low for task complexity")
    if spec.task in (CodeTask.DEBUG, CodeTask.REFACTOR) and not spec.context_code:
        risk_flags.append("DEBUG/REFACTOR requested but context_code is empty")
    if any(k in dl for k in ("secret","password","token")):
        risk_flags.append("Description references secrets -- use env vars only")
    return {"complexity": complexity, "patterns": patterns,
            "async_needed": async_needed, "has_context": bool(spec.context_code.strip()),
            "risk_flags": risk_flags}

# ---------------------------------------------------------------------------
# Code stubs
# ---------------------------------------------------------------------------
_PY_CLIENT_LINES = [
    "# async_api_client.py -- Async HTTP API client with retry logic.",
    "# Generated by Nasus M05 Code Engineer.",
    "from __future__ import annotations",
    "import asyncio, logging",
    "from typing import Any, Dict, Optional",
    "import httpx",
    "logger = logging.getLogger(__name__)",
    "",
    "class APIError(Exception):",
    "    \"Raised when an API call fails after all retries.\"",
    "    def __init__(self, status_code: int, message: str) -> None:",
    "        super().__init__(message)",
    "        self.status_code = status_code",
    "",
    "class AsyncAPIClient:",
    "    \"Async HTTP client with retry and exponential back-off.",
    "    Parameters: base_url, api_key, timeout=10.0, max_retries=3",
    "    \"",
    "    def __init__(self, base_url: str, api_key: str,",
    "                 timeout: float = 10.0, max_retries: int = 3) -> None:",
    "        self.base_url    = base_url.rstrip('/')",
    "        self._api_key    = api_key",
    "        self.timeout     = timeout",
    "        self.max_retries = max_retries",
    "        self._client: Optional[httpx.AsyncClient] = None",
    "",
    "    async def __aenter__(self) -> 'AsyncAPIClient':",
    "        self._client = httpx.AsyncClient(",
    "            base_url=self.base_url,",
    "            headers={'Authorization': f'Bearer {self._api_key}'},",
    "            timeout=self.timeout,",
    "        )",
    "        return self",
    "",
    "    async def __aexit__(self, *_: Any) -> None:",
    "        if self._client:",
    "            await self._client.aclose()",
    "",
    "    async def request(self, method: str, path: str, **kwargs: Any) -> Dict[str, Any]:",
    "        \"Execute HTTP request with retry logic.\"",
    "        last_exc: Optional[Exception] = None",
    "        for attempt in range(1, self.max_retries + 1):",
    "            try:",
    "                if self._client is None:",
    "                    raise RuntimeError('Use as async context manager.')",
    "                response = await self._client.request(method, path, **kwargs)",
    "                response.raise_for_status()",
    "                return response.json()",
    "            except httpx.HTTPStatusError as exc:",
    "                status = exc.response.status_code",
    "                logger.warning('Attempt %d/%d: HTTP %d for %s %s',",
    "                               attempt, self.max_retries, status, method, path)",
    "                if status < 500:",
    "                    raise APIError(status, str(exc)) from exc",
    "                last_exc = exc",
    "            except httpx.RequestError as exc:",
    "                logger.warning('Attempt %d/%d: RequestError: %s', attempt, self.max_retries, exc)",
    "                last_exc = exc",
    "            if attempt < self.max_retries:",
    "                await asyncio.sleep(2 ** attempt)",
    "        raise APIError(0, f'All {self.max_retries} retries failed: {last_exc}') from last_exc",
    "",
    "    async def get(self, path: str, params=None) -> Dict[str, Any]:",
    "        \"HTTP GET.\"",
    "        return await self.request('GET', path, params=params)",
    "",
    "    async def post(self, path: str, json=None) -> Dict[str, Any]:",
    "        \"HTTP POST.\"",
    "        return await self.request('POST', path, json=json)",
    "",
    "    async def put(self, path: str, json=None) -> Dict[str, Any]:",
    "        \"HTTP PUT.\"",
    "        return await self.request('PUT', path, json=json)",
    "",
    "    async def delete(self, path: str) -> Dict[str, Any]:",
    "        \"HTTP DELETE.\"",
    "        return await self.request('DELETE', path)",
]
_PYTHON_API_CLIENT = "\n".join(_PY_CLIENT_LINES)

_PY_TESTS_LINES = [
    "# test_async_api_client.py -- Unit tests for AsyncAPIClient.",
    "import pytest, httpx",
    "from unittest.mock import AsyncMock, MagicMock",
    "from async_api_client import AsyncAPIClient, APIError",
    "",
    "@pytest.mark.asyncio",
    "async def test_get_success():",
    "    client = AsyncAPIClient('https://api.example.com', api_key='test-key')",
    "    mock_response = MagicMock()",
    "    mock_response.json.return_value = {'id': 1}",
    "    mock_response.raise_for_status = MagicMock()",
    "    async with client:",
    "        client._client.request = AsyncMock(return_value=mock_response)",
    "        result = await client.get('/items/1')",
    "    assert result == {'id': 1}",
    "",
    "@pytest.mark.asyncio",
    "async def test_retries_on_500():",
    "    client = AsyncAPIClient('https://api.example.com', api_key='test-key', max_retries=2)",
    "    async with client:",
    "        client._client.request = AsyncMock(",
    "            side_effect=httpx.HTTPStatusError('500', request=MagicMock(), response=MagicMock(status_code=500))",
    "        )",
    "        with pytest.raises(APIError):",
    "            await client.get('/fail')",
    "",
    "@pytest.mark.asyncio",
    "async def test_no_retry_on_400():",
    "    client = AsyncAPIClient('https://api.example.com', api_key='test-key')",
    "    mock_resp = MagicMock(status_code=400)",
    "    async with client:",
    "        client._client.request = AsyncMock(",
    "            side_effect=httpx.HTTPStatusError('400', request=MagicMock(), response=mock_resp)",
    "        )",
    "        with pytest.raises(APIError) as exc_info:",
    "            await client.get('/bad')",
    "    assert exc_info.value.status_code == 400",
]
_PYTHON_TESTS = "\n".join(_PY_TESTS_LINES)

_TS_UTILS_LINES = [
    "// utils.ts -- Utility helpers generated by Nasus M05 Code Engineer",
    "/** Clamps a number between min and max (inclusive). */",
    "export function clamp(value: number, min: number, max: number): number {",
    "  return Math.min(Math.max(value, min), max);",
    "}",
    "/** Deep-clones a plain JSON-serialisable object. */",
    "export function deepClone<T>(obj: T): T {",
    "  return JSON.parse(JSON.stringify(obj));",
    "}",
    "/** Returns a Promise that resolves after ms milliseconds. */",
    "export function sleep(ms: number): Promise<void> {",
    "  return new Promise((resolve) => setTimeout(resolve, ms));",
    "}",
    "/** Retry a Promise-returning function with exponential back-off. */",
    "export async function withRetry<T>(",
    "  fn: () => Promise<T>, maxAttempts = 3, baseDelayMs = 500",
    "): Promise<T> {",
    "  let lastError: unknown;",
    "  for (let attempt = 1; attempt <= maxAttempts; attempt++) {",
    "    try { return await fn(); }",
    "    catch (err) {",
    "      lastError = err;",
    "      if (attempt < maxAttempts) await sleep(baseDelayMs * 2 ** (attempt - 1));",
    "    }",
    "  }",
    "  throw lastError;",
    "}",
]
_TS_UTILS = "\n".join(_TS_UTILS_LINES)

# ---------------------------------------------------------------------------
# 2. generate
# ---------------------------------------------------------------------------
def generate(spec: Spec) -> Union[CodeResult, CodeError]:
    """Generate source code matching the given Spec."""
    if spec.task != CodeTask.GENERATE:
        return _error("Wrong task routed to generate()", "TASK_MISMATCH",
                      f"generate() expects GENERATE, got {spec.task.value}.")
    if spec.language == Language.PYTHON:
        code, fname = _PYTHON_API_CLIENT, "async_api_client.py"
        desc = "Async HTTP API client with retry and context-manager support"
        explain = ("Generated AsyncAPIClient using httpx.AsyncClient with exponential "
                   "back-off retries, context manager lifecycle, and typed convenience methods.")
    elif spec.language == Language.TYPESCRIPT:
        code, fname = _TS_UTILS, "utils.ts"
        desc = "TypeScript utility helpers: clamp, deepClone, sleep, withRetry"
        explain = ("Four typed utilities: clamp, deepClone, sleep, withRetry. "
                   "withRetry uses exponential back-off for resilient async ops.")
    elif spec.language == Language.JAVASCRIPT:
        code = (_TS_UTILS
                .replace(": number", "").replace(": string", "").replace(": boolean", "")
                .replace(": void", "").replace(": unknown", "").replace("<T>", "")
                .replace("(obj: T): T", "(obj)")
                .replace("(value: number, min: number, max: number): number", "(value, min, max)")
                .replace("(ms: number): Promise<void>", "(ms)")
                .replace("fn: () => Promise<T>,", "fn,").replace("): Promise<T> {", ") {"))
        fname, desc = "utils.js", "JavaScript utility helpers (types stripped)"
        explain = "Same utilities as TypeScript version with type annotations removed."
    else:
        lv = spec.language.value
        code = f"# Generated stub for {lv}\n# Task: {spec.description}\n# TODO: implement\n"
        fname, desc = f"generated.{lv}", f"Stub for {lv} -- requires further implementation"
        explain = f"M05 placeholder for {lv}. Full codegen requires LLM backend."

    block = _make_block(spec.language, code, fname, desc)
    tests = []
    if spec.include_tests and spec.language == Language.PYTHON:
        tests.append(_make_block(Language.PYTHON, _PYTHON_TESTS,
                                 "test_async_api_client.py", "pytest unit tests for AsyncAPIClient"))
    result = CodeResult(spec_summary=f"Generate {spec.language.value}: {spec.description[:80]}",
                        blocks=[block], explanation=explain, tests=tests, status=CodeStatus.DONE)
    issues = validate_code_output(result)
    if issues:
        result.review_notes = issues
    return result

# ---------------------------------------------------------------------------
# 3. debug
# ---------------------------------------------------------------------------
_PYTHON_BUG_PATTERNS = [
    (r"except\s+Exception\s+as\s+e\s*:\s*pass", "Bare except swallows errors -- log or re-raise."),
    (r"except\s*:",                                  "Bare except catches BaseException incl. KeyboardInterrupt."),
    (r"==\s*None",                                   "Use 'is None' not == None."),
    (r"\.keys\(\)",                                "Iterating dict.keys() is redundant -- iterate dict directly."),
    (r"open\([^,)]+\)(?!\s*as)",                   "File opened without context manager -- use 'with open(...) as f'."),
    (r"time\.sleep\(\d+\)",                       "Blocking sleep -- use await asyncio.sleep() in async context."),
    (r"\bprint\(",                                  "print() found -- use logging for production code."),
    (r"#\s*(TODO|FIXME|HACK)",                       "Unresolved TODO/FIXME/HACK marker in code."),
]

def debug(spec: Spec) -> Union[CodeResult, CodeError]:
    """Analyse context_code for common error patterns."""
    if not spec.context_code.strip():
        return _error("No code provided for debugging", "MISSING_CONTEXT",
                      "Populate context_code with the code you want debugged.")
    findings = []
    if spec.language == Language.PYTHON:
        for pattern, message in _PYTHON_BUG_PATTERNS:
            if re.search(pattern, spec.context_code, re.IGNORECASE):
                findings.append(message)
    if not findings:
        findings.append("No common bug patterns detected. Manual review recommended.")
    block = _make_block(spec.language, spec.context_code,
                        "debugged_code" + _ext(spec.language), "Original code with debug annotations")
    return CodeResult(
        spec_summary=f"Debug {spec.language.value}: {spec.description[:60]}",
        blocks=[block],
        explanation=("Scanned for common anti-patterns via heuristic regex. "
                     "See review_notes. Apply fixes incrementally and re-run tests."),
        review_notes=findings, status=CodeStatus.DONE)

# ---------------------------------------------------------------------------
# 4. refactor
# ---------------------------------------------------------------------------
def refactor(spec: Spec) -> Union[CodeResult, CodeError]:
    """Apply clean-code transformations to context_code."""
    if not spec.context_code.strip():
        return _error("No code provided for refactoring", "MISSING_CONTEXT",
                      "Populate context_code with the code you want refactored.")
    code, notes = spec.context_code, []
    if spec.language == Language.PYTHON:
        cleaned = "\n".join(line.rstrip() for line in code.splitlines())
        if cleaned != code:
            notes.append("Removed trailing whitespace on all lines.")
            code = cleaned
        if not code.endswith("\n"):
            code += "\n"
            notes.append("Added missing trailing newline.")
        magic = re.findall(r"(?<!\w)(\d{2,})(?!\w)", code)
        noisy = [n for n in magic if n not in ("10","100","200","404","500")]
        if noisy:
            notes.append(f"Magic numbers detected: {set(noisy)} -- extract to named constants.")
        long_lines = [i+1 for i, ln in enumerate(code.splitlines()) if len(ln) > 120]
        if long_lines:
            notes.append(f"Lines exceeding 120 chars: {long_lines[:5]}{'...' if len(long_lines)>5 else ''}")
    if not notes:
        notes.append("No automated transformations applied. Code appears clean.")
    block = _make_block(spec.language, code, "refactored_code" + _ext(spec.language),
                        "Refactored version of provided code")
    return CodeResult(
        spec_summary=f"Refactor {spec.language.value}: {spec.description[:60]}",
        blocks=[block],
        explanation=("Applied: whitespace normalisation, trailing newline, "
                     "magic number detection, long-line flagging."),
        review_notes=notes, status=CodeStatus.DONE)

# ---------------------------------------------------------------------------
# 5. review
# ---------------------------------------------------------------------------
def review(spec: Spec) -> Union[CodeResult, CodeError]:
    """Return a structured code review of context_code."""
    if not spec.context_code.strip():
        return _error("No code provided for review", "MISSING_CONTEXT",
                      "Populate context_code with the code you want reviewed.")
    code, lines, notes = spec.context_code, spec.context_code.splitlines(), []
    notes.append(f"Line count: {len(lines)} total, {_count_lines(code)} non-empty.")
    if spec.language == Language.PYTHON:
        defs   = len(re.findall(r"^\s*def ", code, re.MULTILINE))
        docstr = len(re.findall(r'"""', code)) // 2
        if defs > 0 and docstr < defs:
            notes.append(f"Docstring coverage: {docstr}/{defs} -- add missing docstrings.")
        else:
            notes.append(f"Docstring coverage: {docstr} for {defs} defs -- looks good.")
        typed = len(re.findall(r"def .+\(.*:.*\)", code))
        if typed < defs:
            notes.append(f"Type annotations: {typed}/{defs} typed -- add hints.")
        else:
            notes.append("Type annotations present on all visible function signatures.")
        if "try:" not in code:
            notes.append("No try/except blocks -- consider error handling for external calls.")
        star_imp = re.findall(r"from \S+ import \*", code)
        if star_imp:
            notes.append(f"Wildcard imports: {star_imp} -- use explicit imports.")
    notes.append("Review complete. Apply findings in order of severity.")
    block = _make_block(spec.language, spec.context_code,
                        "reviewed_code" + _ext(spec.language), "Code submitted for review (unchanged)")
    return CodeResult(
        spec_summary=f"Review {spec.language.value}: {spec.description[:60]}",
        blocks=[block],
        explanation="Static analysis review without execution. See review_notes for findings.",
        review_notes=notes, status=CodeStatus.DONE)

# ---------------------------------------------------------------------------
# 6. route_envelope
# ---------------------------------------------------------------------------
def route_envelope(envelope: NasusEnvelope) -> NasusEnvelope:
    """Dispatch NasusEnvelope to correct handler based on spec.task."""
    try:
        payload = envelope.payload or {}
        raw = payload.get("spec")
        if isinstance(raw, dict):
            spec = Spec(
                task=CodeTask(raw["task"]),
                language=Language(raw["language"]),
                description=raw.get("description", ""),
                context_code=raw.get("context_code", ""),
                requirements=raw.get("requirements", []),
                style=CodeStyle(raw.get("style", "clean")),
                max_lines=int(raw.get("max_lines", 200)),
                include_tests=bool(raw.get("include_tests", False)),
                include_docs=bool(raw.get("include_docs", True)),
            )
        elif isinstance(raw, Spec):
            spec = raw
        else:
            raise ValueError("envelope.payload must contain 'spec' key (dict or Spec).")
        dispatch = {
            CodeTask.GENERATE: generate,
            CodeTask.DEBUG:    debug,
            CodeTask.REFACTOR: refactor,
            CodeTask.REVIEW:   review,
            CodeTask.EXPLAIN:  review,
            CodeTask.TEST:     lambda s: generate(Spec(
                task=CodeTask.GENERATE, language=s.language, description=s.description,
                context_code=s.context_code, include_tests=True, style=s.style, max_lines=s.max_lines)),
            CodeTask.CONVERT:  generate,
        }
        handler = dispatch.get(spec.task)
        if not handler:
            raise ValueError(f"No handler for task: {spec.task.value}")
        result = handler(spec)
        if isinstance(result, CodeError):
            envelope.status  = NasusStatus.ERROR
            envelope.payload = {"error": result.to_dict()}
        else:
            envelope.status  = NasusStatus.DONE
            envelope.payload = {"result": result.to_dict()}
    except Exception as exc:  # noqa: BLE001
        envelope.status  = NasusStatus.ERROR
        envelope.payload = {"error": CodeError("Routing failed","ROUTE_ERROR",str(exc)).to_dict()}
    return envelope

# ---------------------------------------------------------------------------
# Runnable demo
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    print("=" * 60)
    print("Nasus M05 Code Engineer -- Demo")
    print("=" * 60)

    print("\n[1] GENERATE: Python async API client")
    spec_gen = Spec(
        task=CodeTask.GENERATE, language=Language.PYTHON,
        description="Async HTTP API client with retry logic and context manager",
        requirements=["Use httpx.AsyncClient","Exponential back-off on 5xx","Context manager","Type hints"],
        style=CodeStyle.PRODUCTION, include_tests=True, max_lines=200,
    )
    print("  Analysis:", json.dumps(analyze_spec(spec_gen), indent=2))
    gen_result = generate(spec_gen)
    if isinstance(gen_result, CodeError):
        print("  ERROR:", gen_result.to_dict())
    else:
        print(f"  Status : {gen_result.status.value}")
        print(f"  Summary: {gen_result.spec_summary}")
        print(f"  Blocks : {[b.filename for b in gen_result.blocks]}")
        print(f"  Tests  : {[t.filename for t in gen_result.tests]}")
        print(f"  Explain: {gen_result.explanation}")

    print("\n[2] REVIEW: generated Python client")
    if isinstance(gen_result, CodeResult) and gen_result.blocks:
        rev = review(Spec(task=CodeTask.REVIEW, language=Language.PYTHON,
                          description="Review the async API client",
                          context_code=gen_result.blocks[0].code))
        if isinstance(rev, CodeResult):
            print(f"  Status: {rev.status.value}")
            for note in rev.review_notes:
                print(f"    - {note}")

    print("\n[3] REFACTOR: messy snippet")
    messy = ("def calculate_total(items):\n"
             "    total = 0\n"
             "    for i in range(len(items)):\n"
             "        total = total + items[i]['price'] * 1.23\n"
             "    return total   \n"
             "\ndef getUser(id):\n"
             "    import requests\n"
             "    r = requests.get('https://api.example.com/users/' + str(id))\n"
             "    return r.json()\n")
    ref = refactor(Spec(task=CodeTask.REFACTOR, language=Language.PYTHON,
                        description="Clean up functions", context_code=messy, style=CodeStyle.CLEAN))
    if isinstance(ref, CodeResult):
        print(f"  Status: {ref.status.value}")
        for note in ref.review_notes:
            print(f"    - {note}")

    print("\n[4] Validation gate")
    if isinstance(gen_result, CodeResult):
        issues = validate_code_output(gen_result)
        print("  Issues:", issues if issues else "None -- all RT checks passed.")

    print("\nDemo complete.")
