use super::registry::{
    CostTier, ModelCapabilities, ModelInfo, Provider, ToolCallingSupport,
};

pub fn default_model_registry() -> Vec<ModelInfo> {
    vec![
        // ── Premium ──────────────────────────────────────────────────────────
        ModelInfo {
            id: "anthropic/claude-opus-4-5".into(),
            display_name: "Claude Opus 4.5".into(),
            provider: Provider::Anthropic,
            capabilities: ModelCapabilities {
                reasoning: 0.98,
                coding: 0.95,
                writing: 0.97,
                speed: 0.30,
                instruction_following: 0.97,
            },
            tool_calling: ToolCallingSupport::Strong,
            cost_tier: CostTier::Premium,
            context_window: 200_000,
            enabled: true,
        },
        // ── Standard ─────────────────────────────────────────────────────────
        ModelInfo {
            id: "anthropic/claude-sonnet-4-20250514".into(),
            display_name: "Claude Sonnet 4".into(),
            provider: Provider::Anthropic,
            capabilities: ModelCapabilities {
                reasoning: 0.95,
                coding: 0.96,
                writing: 0.93,
                speed: 0.68,
                instruction_following: 0.96,
            },
            tool_calling: ToolCallingSupport::Strong,
            cost_tier: CostTier::Standard,
            context_window: 200_000,
            enabled: true,
        },
        ModelInfo {
            id: "anthropic/claude-sonnet-4-5".into(),
            display_name: "Claude Sonnet 4.5".into(),
            provider: Provider::Anthropic,
            capabilities: ModelCapabilities {
                reasoning: 0.93,
                coding: 0.94,
                writing: 0.92,
                speed: 0.70,
                instruction_following: 0.95,
            },
            tool_calling: ToolCallingSupport::Strong,
            cost_tier: CostTier::Standard,
            context_window: 200_000,
            enabled: true,
        },
        ModelInfo {
            id: "anthropic/claude-3.7-sonnet".into(),
            display_name: "Claude 3.7 Sonnet".into(),
            provider: Provider::Anthropic,
            capabilities: ModelCapabilities {
                reasoning: 0.91,
                coding: 0.93,
                writing: 0.90,
                speed: 0.72,
                instruction_following: 0.93,
            },
            tool_calling: ToolCallingSupport::Strong,
            cost_tier: CostTier::Standard,
            context_window: 200_000,
            enabled: true,
        },
        ModelInfo {
            id: "openai/gpt-4.1".into(),
            display_name: "GPT-4.1".into(),
            provider: Provider::OpenAI,
            capabilities: ModelCapabilities {
                reasoning: 0.92,
                coding: 0.93,
                writing: 0.90,
                speed: 0.70,
                instruction_following: 0.93,
            },
            tool_calling: ToolCallingSupport::Strong,
            cost_tier: CostTier::Standard,
            context_window: 1_000_000,
            enabled: true,
        },
        ModelInfo {
            id: "google/gemini-2.5-pro-preview".into(),
            display_name: "Gemini 2.5 Pro".into(),
            provider: Provider::Google,
            capabilities: ModelCapabilities {
                reasoning: 0.90,
                coding: 0.88,
                writing: 0.87,
                speed: 0.75,
                instruction_following: 0.88,
            },
            tool_calling: ToolCallingSupport::Strong,
            cost_tier: CostTier::Standard,
            context_window: 1_000_000,
            enabled: true,
        },
        // DeepSeek R1 — reasoning model, now supports tool calling
        ModelInfo {
            id: "deepseek/deepseek-r1".into(),
            display_name: "DeepSeek R1".into(),
            provider: Provider::DeepSeek,
            capabilities: ModelCapabilities {
                reasoning: 0.97,
                coding: 0.95,
                writing: 0.84,
                speed: 0.45,
                instruction_following: 0.90,
            },
            tool_calling: ToolCallingSupport::Strong,
            cost_tier: CostTier::Standard,
            context_window: 128_000,
            enabled: true,
        },
        // DeepSeek R1-0528 — updated R1 checkpoint with tool calling
        ModelInfo {
            id: "deepseek/deepseek-r1-0528".into(),
            display_name: "DeepSeek R1-0528".into(),
            provider: Provider::DeepSeek,
            capabilities: ModelCapabilities {
                reasoning: 0.98,
                coding: 0.96,
                writing: 0.85,
                speed: 0.40,
                instruction_following: 0.91,
            },
            tool_calling: ToolCallingSupport::Strong,
            cost_tier: CostTier::Standard,
            context_window: 128_000,
            enabled: true,
        },
        // ── Budget ───────────────────────────────────────────────────────────
        ModelInfo {
            id: "anthropic/claude-3-5-haiku".into(),
            display_name: "Claude 3.5 Haiku".into(),
            provider: Provider::Anthropic,
            capabilities: ModelCapabilities {
                reasoning: 0.78,
                coding: 0.80,
                writing: 0.77,
                speed: 0.95,
                instruction_following: 0.82,
            },
            tool_calling: ToolCallingSupport::Strong,
            cost_tier: CostTier::Budget,
            context_window: 200_000,
            enabled: true,
        },
        ModelInfo {
            id: "google/gemini-2.0-flash-001".into(),
            display_name: "Gemini 2.0 Flash".into(),
            provider: Provider::Google,
            capabilities: ModelCapabilities {
                reasoning: 0.80,
                coding: 0.82,
                writing: 0.78,
                speed: 0.92,
                instruction_following: 0.80,
            },
            tool_calling: ToolCallingSupport::Moderate,
            cost_tier: CostTier::Budget,
            context_window: 1_000_000,
            enabled: true,
        },
        // DeepSeek V3 / V3.2 (deepseek-chat)
        ModelInfo {
            id: "deepseek/deepseek-chat".into(),
            display_name: "DeepSeek V3".into(),
            provider: Provider::DeepSeek,
            capabilities: ModelCapabilities {
                reasoning: 0.88,
                coding: 0.90,
                writing: 0.82,
                speed: 0.80,
                instruction_following: 0.85,
            },
            tool_calling: ToolCallingSupport::Strong,
            cost_tier: CostTier::Budget,
            context_window: 128_000,
            enabled: true,
        },
        ModelInfo {
            id: "openai/gpt-4.1-mini".into(),
            display_name: "GPT-4.1 Mini".into(),
            provider: Provider::OpenAI,
            capabilities: ModelCapabilities {
                reasoning: 0.80,
                coding: 0.82,
                writing: 0.78,
                speed: 0.90,
                instruction_following: 0.82,
            },
            tool_calling: ToolCallingSupport::Strong,
            cost_tier: CostTier::Budget,
            context_window: 1_000_000,
            enabled: true,
        },
        // ── Free ─────────────────────────────────────────────────────────────
        ModelInfo {
            id: "google/gemini-2.5-flash:free".into(),
            display_name: "Gemini 2.5 Flash (Free)".into(),
            provider: Provider::Google,
            capabilities: ModelCapabilities {
                reasoning: 0.78,
                coding: 0.78,
                writing: 0.75,
                speed: 0.90,
                instruction_following: 0.78,
            },
            tool_calling: ToolCallingSupport::Moderate,
            cost_tier: CostTier::Free,
            context_window: 1_000_000,
            enabled: true,
        },
        ModelInfo {
            id: "deepseek/deepseek-r1:free".into(),
            display_name: "DeepSeek R1 (Free)".into(),
            provider: Provider::DeepSeek,
            capabilities: ModelCapabilities {
                reasoning: 0.97,
                coding: 0.95,
                writing: 0.84,
                speed: 0.40,
                instruction_following: 0.90,
            },
            tool_calling: ToolCallingSupport::Strong,
            cost_tier: CostTier::Free,
            context_window: 128_000,
            enabled: true,
        },
        ModelInfo {
            id: "meta-llama/llama-3.3-70b-instruct:free".into(),
            display_name: "Llama 3.3 70B (Free)".into(),
            provider: Provider::Meta,
            capabilities: ModelCapabilities {
                reasoning: 0.80,
                coding: 0.78,
                writing: 0.78,
                speed: 0.85,
                instruction_following: 0.78,
            },
            tool_calling: ToolCallingSupport::Moderate,
            cost_tier: CostTier::Free,
            context_window: 128_000,
            enabled: true,
        },
    ]
}
