use tauri::State;
use crate::AppState;
use crate::utils::zip::create_project_zip;
use std::path::PathBuf;

fn get_downloads_dir() -> PathBuf {
    if let Some(home) = dirs_next::home_dir() {
        home.join("Downloads")
    } else {
        std::env::temp_dir()
    }
}

fn build_readme(project_name: &str) -> String {
    format!(
        "# {}\n\nGenerated by Nasus Web Designer.\n\n## Files\n\n- `index.html` — Main HTML file\n- `style.css` — Stylesheet\n- `script.js` — JavaScript\n\n## How to Run\n\nOpen `index.html` in any modern web browser.\n\n---\n*Built with [Nasus Web Designer](https://nasus.app)*\n",
        project_name
    )
}

fn embed_assets(html: &str, css: &str, js: &str) -> String {
    // If the HTML already has a full document structure, inject CSS/JS into it
    if html.contains("</head>") && html.contains("</body>") {
        let with_css = if !css.is_empty() {
            html.replacen(
                "</head>",
                &format!("<link rel=\"stylesheet\" href=\"style.css\">\n</head>"),
                1,
            )
        } else {
            html.to_string()
        };
        let with_js = if !js.is_empty() {
            with_css.replacen(
                "</body>",
                &format!("<script src=\"script.js\"></script>\n</body>"),
                1,
            )
        } else {
            with_css
        };
        with_js
    } else {
        // Wrap in a full document
        format!(
            "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"UTF-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n<title>{}</title>\n{}\n</head>\n<body>\n{}\n{}\n</body>\n</html>",
            "Nasus Project",
            if !css.is_empty() { "<link rel=\"stylesheet\" href=\"style.css\">" } else { "" },
            html,
            if !js.is_empty() { "<script src=\"script.js\"></script>" } else { "" },
        )
    }
}

#[tauri::command]
pub async fn export_project(
    html: String,
    css: String,
    js: String,
    project_name: String,
    _state: State<'_, AppState>,
) -> Result<String, String> {
    let safe_name: String = project_name
        .chars()
        .map(|c| if c.is_alphanumeric() || c == '-' || c == '_' { c } else { '_' })
        .collect();

    let downloads = get_downloads_dir();
    let zip_path = downloads.join(format!("{}.zip", safe_name));
    let zip_path_str = zip_path.to_string_lossy().to_string();

    let index_html = embed_assets(&html, &css, &js);

    let files = vec![
        ("index.html".to_string(), index_html),
        ("style.css".to_string(), css),
        ("script.js".to_string(), js),
        ("README.md".to_string(), build_readme(&project_name)),
    ];

    create_project_zip(files, &zip_path_str)
        .map_err(|e| format!("Failed to create zip: {}", e))?;

    Ok(zip_path_str)
}
